[manifest]
version = "1.0.0"
priority = 0

# Change the save directory to not overwrite any saves. 
# TowersOfScale is what the mod injector picks for a mod directory, so this was the easiest path forward
[[patches]]
[patches.pattern]
target = "conf.lua"
position = "at"
pattern = "t.identity = \"towers_of_scale\"      -- The name of the save directory (string)"
payload = 't.identity = "TowersOfScale"'
match_indent = true


#Mount the mod assets
[[patches]]
[patches.pattern]
target = "main.lua"
position = "before"
pattern = 'local Settings = require "settings"'
payload = 'love.filesystem.mount("Mods/CursedMod.zip", "CursedMod", true)'
match_indent = true

#Color pallettes
#[[patches]]
#[patches.pattern]
#target = "settings.lua"
#position = "after"
#pattern = 'local PALETTES = {'
#payload = '''
#    {{0.224, 0.133, 0.021},{0.078, 0.313, 0.078},{0.181, 0.517, 0.066},{0.557, 0.323, 0.127},{0.821, 0.439, 0.061}},
#'''
#match_indent = true

# DEBUG


#[[patches]]
#[patches.pattern]
#target = "game.lua"
#pattern = "local ents = tonumber(reader_it())"
#position = "after"
#payload = '''
#print("entity count: " .. ents)
#'''
#match_indent = true

#[[patches]]
#[patches.pattern]
#target = "game.lua"
#pattern = "local ent_type = floor.entities[i].type"
#position = "before"
#payload = '''
#print(i .. ": " floor.entities[i])
#'''
#match_indent = true



#[[patches]]
#[patches.pattern]
#target = "leveldata.lua"
#position = "before"
#pattern = 'for i=1,15 do'
#payload = 'print("loading floor " .. self[f].name)'
#match_indent = true
